require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PerspectivesController do

  def mock_perspective(stubs={})
    @mock_perspective ||= mock_model(Perspective, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all perspectives as @perspectives" do
      Perspective.stub(:all) { [mock_perspective] }
      get :index
      assigns(:perspectives).should eq([mock_perspective])
    end
  end

  describe "GET show" do
    it "assigns the requested perspective as @perspective" do
      Perspective.stub(:find).with("37") { mock_perspective }
      get :show, :id => "37"
      assigns(:perspective).should be(mock_perspective)
    end
  end

  describe "GET new" do
    it "assigns a new perspective as @perspective" do
      Perspective.stub(:new) { mock_perspective }
      get :new
      assigns(:perspective).should be(mock_perspective)
    end
  end

  describe "GET edit" do
    it "assigns the requested perspective as @perspective" do
      Perspective.stub(:find).with("37") { mock_perspective }
      get :edit, :id => "37"
      assigns(:perspective).should be(mock_perspective)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created perspective as @perspective" do
        Perspective.stub(:new).with({'these' => 'params'}) { mock_perspective(:save => true) }
        post :create, :perspective => {'these' => 'params'}
        assigns(:perspective).should be(mock_perspective)
      end

      it "redirects to the created perspective" do
        Perspective.stub(:new) { mock_perspective(:save => true) }
        post :create, :perspective => {}
        response.should redirect_to(perspective_url(mock_perspective))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved perspective as @perspective" do
        Perspective.stub(:new).with({'these' => 'params'}) { mock_perspective(:save => false) }
        post :create, :perspective => {'these' => 'params'}
        assigns(:perspective).should be(mock_perspective)
      end

      it "re-renders the 'new' template" do
        Perspective.stub(:new) { mock_perspective(:save => false) }
        post :create, :perspective => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested perspective" do
        Perspective.stub(:find).with("37") { mock_perspective }
        mock_perspective.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :perspective => {'these' => 'params'}
      end

      it "assigns the requested perspective as @perspective" do
        Perspective.stub(:find) { mock_perspective(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:perspective).should be(mock_perspective)
      end

      it "redirects to the perspective" do
        Perspective.stub(:find) { mock_perspective(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(perspective_url(mock_perspective))
      end
    end

    describe "with invalid params" do
      it "assigns the perspective as @perspective" do
        Perspective.stub(:find) { mock_perspective(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:perspective).should be(mock_perspective)
      end

      it "re-renders the 'edit' template" do
        Perspective.stub(:find) { mock_perspective(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested perspective" do
      Perspective.stub(:find).with("37") { mock_perspective }
      mock_perspective.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the perspectives list" do
      Perspective.stub(:find) { mock_perspective }
      delete :destroy, :id => "1"
      response.should redirect_to(perspectives_url)
    end
  end

end
